### PR TITLE
New UI

### PR DESCRIPTION
**Pull request by kungharrison**
New font, buttons, colors, icons to modernize UI. Also fixed some graphical bugs

### CODE REVIEW

**Comment by WojtekTB** [comment]
Hey, so I love the changes overall but it seems that you removed the image files for buttons before you made this PR. I think it was not intentional but let me know if it was and I will just change the button names back

**Comment by WojtekTB** [comment]
> Hey, so I love the changes overall but it seems that you removed the image files for buttons before you made this PR. I think it was not intentional but let me know if it was and I will just change the button names back

actually, I think I will just revert the file removal commit and keep the UI changes. Most of those files were actually used

**Comment by kungharrison** [comment]
It should work without the image files, I changed it so it's getting them from google api using url instead of the asset so it's unnecessary.

**Comment by kungharrison** [comment]
Also it appears only the ucsd-icon-128 is being used so I removed the other duplicate icon but it should work without those 4 pngs

**Comment by kungharrison** [comment]
If you want you can keep the pngs, they just aren't being used though.

**Comment by WojtekTB** [comment]
hmm I think you are mistaking, without the button pngs they did not show up. I am keeping the full sized image just so that I don't have to look for it later lol.

**Comment by WojtekTB** [comment]
I made some small design changes and it looks good to me now, thanks for your contribution :)

**Pull request merged**
